const LOCAL_HOSTS = new Set(['localhost', '127.0.0.1', '::1']);
const currentHost = globalThis.location?.hostname || '';
const configuredUrl = import.meta.env.VITE_API_URL?.trim();
export const API_URL = configuredUrl || (LOCAL_HOSTS.has(currentHost) ? 'http://localhost:8000/api' : '/api');
const TOKEN_KEY = 'zawsze-auth-token';
export function getStoredToken(){return localStorage.getItem(TOKEN_KEY)||'';}
export function setStoredToken(token){if(token)localStorage.setItem(TOKEN_KEY,token);else localStorage.removeItem(TOKEN_KEY);}
async function parseResponse(response){const contentType=response.headers.get('content-type')||'';if(contentType.includes('application/json'))return response.json();return response.text();}
export async function apiRequest(path,options={}){const token=getStoredToken();const isFormData=options.body instanceof FormData;let response;try{response=await fetch(`${API_URL}${path.replace(/^\/api/,'')}`,{...options,headers:{Accept:'application/json',...(!isFormData&&options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`} : {}),...(options.headers||{})},body:options.body&&!isFormData&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});}catch{throw new Error(`Cannot reach the Zawsze backend at ${API_URL}. Make sure Laravel is running on port 8000.`);}const data=await parseResponse(response);if(!response.ok){if(response.status===401)setStoredToken('');const message=typeof data==='object'?(data?.message||data?.error||Object.values(data?.errors||{})?.flat?.()?.[0]):data;const error=new Error(message||`Request failed with status ${response.status}`);error.status=response.status;error.data=data;throw error;}return data;}
export function apiUpload(path,formData,onProgress=()=>{}){const token=getStoredToken();return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`${API_URL}${path.replace(/^\/api/,'')}`);xhr.setRequestHeader('Accept','application/json');if(token)xhr.setRequestHeader('Authorization',`Bearer ${token}`);xhr.upload.onprogress=(event)=>{if(event.lengthComputable)onProgress(Math.round((event.loaded/event.total)*100));};xhr.onerror=()=>reject(new Error('Upload failed because the backend could not be reached.'));xhr.onload=()=>{let payload=xhr.responseText;try{payload=JSON.parse(xhr.responseText);}catch{}if(xhr.status>=200&&xhr.status<300)resolve(payload);else{if(xhr.status===401)setStoredToken('');const message=typeof payload==='object'?(payload?.message||payload?.error||Object.values(payload?.errors||{})?.flat?.()?.[0]):payload;const error=new Error(message||`Upload failed with status ${xhr.status}`);error.status=xhr.status;reject(error);}};xhr.send(formData);});}
export async function apiDownload(path,filename='zawsze-download'){const token=getStoredToken();const response=await fetch(`${API_URL}${path.replace(/^\/api/,'')}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok){const text=await response.text();throw new Error(text||`Download failed with status ${response.status}`);}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}
